import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

export const metadata = {
    title: 'Disclaimer | ExamGen AI',
    description: 'Disclaimer for ExamGen AI exam paper generator. Information about AI-generated content, accuracy, and usage responsibilities.',
};

export default function DisclaimerPage() {
    return (
        <>
            <Navbar />
            <div style={{ paddingTop: '100px', minHeight: '100vh', paddingBottom: 'var(--space-12)' }}>
                <div className="container" style={{ maxWidth: '800px' }}>
                    <div className="glass-card" style={{ padding: 'var(--space-10)' }}>
                        <h1 className="gradient-text" style={{ marginBottom: 'var(--space-6)' }}>Disclaimer</h1>
                        <p style={{ color: 'var(--text-secondary)', marginBottom: 'var(--space-2)' }}>Last updated: February 22, 2026</p>

                        <div style={{ lineHeight: 1.8, color: 'var(--text-secondary)' }}>
                            <h2 style={{ color: 'var(--text-primary)', marginTop: 'var(--space-8)', marginBottom: 'var(--space-3)', fontSize: 'var(--text-xl)' }}>General Information</h2>
                            <p>The information provided by ExamGen AI ("we", "us", or "our") on examgen.pk (the "Site") is for general informational and educational purposes only. All information on the Site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information on the Site.</p>

                            <h2 style={{ color: 'var(--text-primary)', marginTop: 'var(--space-8)', marginBottom: 'var(--space-3)', fontSize: 'var(--text-xl)' }}>AI-Generated Content</h2>
                            <p>ExamGen AI uses artificial intelligence to generate exam questions. While we strive for accuracy, AI-generated content may contain errors, inaccuracies, or outdated information. Users are responsible for:</p>
                            <ul style={{ paddingLeft: 'var(--space-6)', marginTop: 'var(--space-3)' }}>
                                <li>Reviewing all generated questions before use</li>
                                <li>Verifying accuracy of answers and content</li>
                                <li>Ensuring content meets their educational standards</li>
                                <li>Making appropriate modifications as needed</li>
                            </ul>

                            <h2 style={{ color: 'var(--text-primary)', marginTop: 'var(--space-8)', marginBottom: 'var(--space-3)', fontSize: 'var(--text-xl)' }}>Educational Purpose</h2>
                            <p>The exam papers generated by this platform are intended for educational purposes only. They should be used as supplementary teaching tools and not as the sole basis for student assessment. Teachers and institutions should use their professional judgment when utilizing AI-generated content.</p>

                            <h2 style={{ color: 'var(--text-primary)', marginTop: 'var(--space-8)', marginBottom: 'var(--space-3)', fontSize: 'var(--text-xl)' }}>Textbook Content</h2>
                            <p>Official Punjab Curriculum & Textbook Board (PCTB) textbooks are provided free of charge on the official PCTB portal. ExamGen AI uses these publicly available educational materials solely for the purpose of generating exam questions. All credit for textbook content belongs to PCTB and the respective authors.</p>

                            <h2 style={{ color: 'var(--text-primary)', marginTop: 'var(--space-8)', marginBottom: 'var(--space-3)', fontSize: 'var(--text-xl)' }}>External Links</h2>
                            <p>The Site may contain links to external websites. We do not control the content or nature of these external sites and are not responsible for their content, privacy policies, or practices.</p>

                            <h2 style={{ color: 'var(--text-primary)', marginTop: 'var(--space-8)', marginBottom: 'var(--space-3)', fontSize: 'var(--text-xl)' }}>Advertisements</h2>
                            <p>This website displays advertisements served by Google AdSense. These ads are personalized based on your browsing history and interests. Google's use of advertising cookies enables it and its partners to serve ads based on your visit to our site and/or other sites on the Internet. You may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" style={{ color: 'var(--primary-400)' }}>Google Ad Settings</a>.</p>

                            <h2 style={{ color: 'var(--text-primary)', marginTop: 'var(--space-8)', marginBottom: 'var(--space-3)', fontSize: 'var(--text-xl)' }}>Limitation of Liability</h2>
                            <p>Under no circumstance shall we have any liability to you for any loss or damage of any kind incurred as a result of the use of the site or reliance on any information provided on the site. Your use of the site and your reliance on any information on the site is solely at your own risk.</p>

                            <h2 style={{ color: 'var(--text-primary)', marginTop: 'var(--space-8)', marginBottom: 'var(--space-3)', fontSize: 'var(--text-xl)' }}>Contact Us</h2>
                            <p>If you have any questions about this Disclaimer, please contact us at <a href="mailto:mushtaqzain180@gmail.com" style={{ color: 'var(--primary-400)' }}>mushtaqzain180@gmail.com</a>.</p>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    );
}
